version: '3.9'

services:

  db:
    image: postgres:16.3-alpine3.19
    restart: always
    container_name: postgres-name
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
